// GENERATED by tools/gen_fonts.py - do not edit. DejaVu Sans (Bitstream Vera licence, see tools/fonts/README).
#pragma once
#include <stdint.h>

struct AAGlyph { uint32_t off; uint8_t adv, w, h; int8_t bx; int8_t by; };  // by: bitmap top below line top
struct AAFont {
    uint8_t px, ascent, height;     // height = ascent + descent (line box)
    uint16_t count;
    const uint16_t *cps;            // sorted code points
    const AAGlyph *glyphs;
    const uint8_t *bitmap;          // 8-bit alpha, w*h per glyph at glyph.off
};

extern const AAFont aaR14;
extern const AAFont aaR17;
extern const AAFont aaR20;
extern const AAFont aaR24;
extern const AAFont aaB17;
extern const AAFont aaB20;
extern const AAFont aaB24;
extern const AAFont aaB30;
extern const AAFont aaB44;
extern const AAFont aaB90;
