#!/usr/bin/env python3
"""Render DejaVu Sans / Bold into 8-bit alpha glyph bitmaps -> src/ui/fonts_aa.{h,cpp}.
Usage: python3 tools/gen_fonts.py   (needs Pillow)"""
import os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "ui")
REG = os.path.join(HERE, "fonts", "DejaVuSans.ttf")
BOLD = os.path.join(HERE, "fonts", "DejaVuSans-Bold.ttf")

FULL = [chr(c) for c in range(32, 127)] + ["°", "–", "·", "×"]
NUM = list(" 0123456789.-g°C")   # huge soot value only

# (C identifier, ttf, px, charset)
FONTS = [
    ("aaR14", REG, 14, FULL), ("aaR17", REG, 17, FULL), ("aaR20", REG, 20, FULL),
    ("aaR24", REG, 24, FULL),
    ("aaB17", BOLD, 17, FULL), ("aaB20", BOLD, 20, FULL), ("aaB24", BOLD, 24, FULL),
    ("aaB30", BOLD, 30, FULL), ("aaB44", BOLD, 44, FULL), ("aaB90", BOLD, 90, NUM),
]

def render(ttf, px, chars):
    f = ImageFont.truetype(ttf, px)
    asc, desc = f.getmetrics()
    glyphs, blob, cps = [], bytearray(), []
    for ch in sorted(chars, key=ord):
        adv = int(round(f.getlength(ch)))
        l, t, r, b = f.getbbox(ch, anchor="ls")
        w, h = max(0, r - l), max(0, b - t)
        off = len(blob)
        if w and h:
            im = Image.new("L", (w, h), 0)
            ImageDraw.Draw(im).text((-l, -t), ch, font=f, fill=255, anchor="ls")
            blob += im.tobytes()
        glyphs.append((off, adv, w, h, l, asc + t))
        cps.append(ord(ch))
    return asc, asc + desc, cps, glyphs, blob

def main():
    h = ["// GENERATED by tools/gen_fonts.py - do not edit. DejaVu Sans (Bitstream Vera licence, see tools/fonts/README).",
         "#pragma once", "#include <stdint.h>", "",
         "struct AAGlyph { uint32_t off; uint8_t adv, w, h; int8_t bx; int8_t by; };  // by: bitmap top below line top",
         "struct AAFont {",
         "    uint8_t px, ascent, height;     // height = ascent + descent (line box)",
         "    uint16_t count;",
         "    const uint16_t *cps;            // sorted code points",
         "    const AAGlyph *glyphs;",
         "    const uint8_t *bitmap;          // 8-bit alpha, w*h per glyph at glyph.off",
         "};", ""]
    c = ['// GENERATED by tools/gen_fonts.py - do not edit.', '#include "fonts_aa.h"', ""]
    total = 0
    for name, ttf, px, chars in FONTS:
        asc, hgt, cps, gl, blob = render(ttf, px, chars)
        total += len(blob)
        h.append(f"extern const AAFont {name};")
        c.append(f"static const uint8_t {name}_bm[] = {{")
        for i in range(0, len(blob), 32):
            c.append("    " + ",".join(str(x) for x in blob[i:i + 32]) + ",")
        if not blob: c.append("    0")
        c.append("};")
        c.append(f"static const uint16_t {name}_cp[] = {{" + ",".join(map(str, cps)) + "};")
        c.append(f"static const AAGlyph {name}_g[] = {{")
        for g in gl: c.append("    {%d,%d,%d,%d,%d,%d}," % g)
        c.append("};")
        c.append(f"const AAFont {name} = {{{px},{asc},{hgt},{len(cps)},{name}_cp,{name}_g,{name}_bm}};")
        c.append("")
        print(f"{name}: {len(blob)} bytes bitmap, {len(cps)} glyphs, line {hgt}")
    print("total bitmap bytes", total)
    open(os.path.join(OUT, "fonts_aa.h"), "w").write("\n".join(h) + "\n")
    open(os.path.join(OUT, "fonts_aa.cpp"), "w").write("\n".join(c) + "\n")

if __name__ == "__main__":
    main()
